import os
cwd = os.path.dirname(Dir('.').srcnode().abspath)
ff_path = os.path.join(cwd, 'src/')
lib_path = os.path.join(cwd, 'build/')
print ff_path

env = Environment(CXXFLAGS='-std=c++11',
    CPPPATH=ff_path,
    LIBPATH=lib_path)

libs = ['matio', 'ffsae']
env.Program('test_matio.cpp', LIBS=['matio'])
env.Program('test_slice.cpp', LIBS=libs)
