import os
cwd = os.path.dirname(Dir('.').srcnode().abspath)
ff_path = os.path.join(cwd, 'src/')
lib_path = os.path.join(cwd, 'build/')


env = Environment(CXXFLAGS='-std=c++11',
    CPPPATH=ff_path,
    LIBPATH=lib_path,
    RPATH=[lib_path, '/usr/local/lib'])

libs = ['matio', 'ffsae']
env.Program('test_matio.cpp', LIBS=['matio'])
env.Program('test_slice.cpp', LIBS=libs)

env.Program('test_blaze.cpp', LIBS=libs+['blaze'])
env.Program('test_dtype.cpp', LIBS=libs+['blaze'])
env.Program('test_sae.cpp', LIBS=libs + ['blaze'])
env.Program('test_math.cpp', LIBS=libs + ['blaze'])
